/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>

#include "stm32f407xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* -------------------- Delay Constant -------------------- */
#define DELAY_COUNT    (10000UL)           // Rough delay count

/* -------------------- Function Prototypes -------------------- */
void delay(volatile uint32_t count);

void gpio_init(void)
{
	// 1. Enable clock access to GPIOA and GPIOD
	RCC_AHB1ENR |= (RCC_AHB1ENR_GPIOA_EN | RCC_AHB1ENR_GPIOD_EN);

	// 2. Set PA0 as input (MODER0 = 0b00)
	GPIOA_MODER &= ~(3 << (BUTTON_PIN * 2));  // Clear mode bits for pin A0

	// 3. Set PD12-PD15 as output (MODER = 0b01)
	for (int i = 0; i < LED_COUNT; i++) {
		GPIOD_MODER &= ~(3 << ((LED_START_PIN + i) * 2));
		GPIOD_MODER |=  (1 << ((LED_START_PIN + i)  * 2));
	}
}

void leds_display(uint8_t value) {
	//Clear all LEDs
	GPIOD_ODR &= ~(0xF << LED_START_PIN);
	//Set LEDs according to lower 4 bits
	GPIOD_ODR |= ((value & 0xF) << LED_START_PIN);
}
int main(void)
{
	gpio_init();

	uint8_t counter = 0;
	bool button_last = false;

	while(1) {
		bool button_now = (GPIOA_IDR & (1 << BUTTON_PIN)) !=0;

		//Detect rising edge (LOW -> HIGH)
		if(!button_last && button_now) {
			counter = (counter + 1) & 0x0F; // Count 0 - 15, wrap
			leds_display(counter);
		}

		button_last = button_now;
		delay(DELAY_COUNT); //Debounce + CPU load reduction
	}
}

/* -------------------- Delay Function -------------------- */
/**
 * @brief  Simple blocking delay using a loop
 * @param  count: number of iterations to delay
 */
void delay(volatile uint32_t count)
{
    while (count--)
    {
        __asm__("nop");  // No Operation – waste one CPU cycle
    }
}
